name: Trivy Filesystem Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  trivy_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
- uses: actions/upload-artifact@v4
      
- name: Install Trivy
        run: |
          TRIVY_VERSION=$(curl -s https://api.github.com/repos/aquasecurity/trivy/releases/latest | grep tag_name | cut -d '"' -f 4)
          curl -L https://github.com/aquasecurity/trivy/releases/download/${TRIVY_VERSION}/trivy_${TRIVY_VERSION#v}_Linux-64bit.tar.gz -o trivy.tar.gz
          tar zxvf trivy.tar.gz
          sudo mv trivy /usr/local/bin/
          trivy --version

      - name: Run Trivy Scan on filesystem
        run: trivy fs --exit-code 0 --severity CRITICAL,HIGH --format table --output trivy-report.txt .

      - name: Upload Trivy Report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: trivy-report.txt

