name: Trivy Filesystem Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  trivy_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget tar
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.51.1_Linux-64bit.tar.gz
          tar zxvf trivy_0.51.1_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/
          trivy --version

      - name: Run Trivy Filesystem Scan
        run: |
          mkdir -p trivy-results
          trivy fs --exit-code 0 --severity CRITICAL,HIGH --format table --output trivy-results/trivy-report.txt .

      - name: Upload Trivy Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-report
          path: trivy-results/trivy-report.txt

